import { spawn } from 'child_process'; import fs from 'fs';
const CH='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const ch=spawn(CH,['--headless=new','--disable-gpu','--hide-scrollbars','--remote-debugging-port=9335',
  '--window-size=1440,1000','--no-first-run','--no-default-browser-check','about:blank'],{stdio:'ignore'});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
await sleep(1800);
const list=await (await fetch('http://127.0.0.1:9335/json/list')).json();
const ws=new (await import('ws')).WebSocket(list.find(t=>t.type==='page').webSocketDebuggerUrl);
await new Promise(r=>ws.once('open',r));
let id=0; const pend=new Map();
ws.on('message',m=>{const d=JSON.parse(m);if(pend.has(d.id)){pend.get(d.id)(d);pend.delete(d.id)}});
const send=(m,p={})=>new Promise(r=>{const n=++id;pend.set(n,r);ws.send(JSON.stringify({id:n,method:m,params:p}))});
const ev=e=>send('Runtime.evaluate',{expression:e,awaitPromise:false});
const shot=async f=>{const r=await send('Page.captureScreenshot',{format:'png'});
  fs.writeFileSync('shots/'+f,Buffer.from(r.result.data,'base64'));console.log('shots/'+f)};
await send('Page.enable');
await send('Page.navigate',{url:'file:///Users/lucianolupo/projects/micro-tribunal/index.html'});
await sleep(3000);
await ev(`document.getElementById('demo').scrollIntoView()`); await sleep(900);
await shot('demo-1-catalogo.png');
await ev(`document.querySelector('[data-prod="zap"]').click()`); await sleep(400);
await ev(`document.querySelector('[data-act="pagar"]').click()`); await sleep(3600);
await shot('demo-2-garantia.png');
await ev(`document.querySelector('[data-act="reclamo"]').click()`); await sleep(400);
await ev(`document.querySelector('[data-ev="foto"]').click();document.querySelector('[data-ev="chat"]').click()`);
await sleep(300); await shot('demo-3-disputa.png');
await ev(`document.querySelector('[data-act="enviar"]').click()`); await sleep(4500);
await ev(`document.querySelector('[data-act="correr"]').click()`); await sleep(5500);
await shot('demo-4-fallo.png');
await ev(`document.querySelector('[data-act="cobrar"]').click()`); await sleep(500);
await ev(`document.querySelector('[data-act="escanear"]').click()`); await sleep(4200);
await shot('demo-5-cobrado.png');
ws.close(); ch.kill();
